export { default as Logo } from './logo.svg?raw'
export { default as LogoMinimized } from './logo-minimized.svg?raw'
export { default as Home } from './home.svg?raw'
export { default as Budgets } from './budgets.svg?raw'
export { default as Pots } from './pots.svg?raw'
export { default as PotsOutline } from './pots-outline.svg?raw'
export { default as Transactions } from './transactions.svg?raw'
export { default as Reccuring } from './reccuring.svg?raw'
export { default as Arrow } from './arrow.svg?raw'
export { default as ArrowRight } from './arrow-right.svg?raw'
export { default as OK } from './ok.svg?raw'
export { default as NotOK } from './notOk.svg?raw'
export { default as ReccuringWhite } from './reccuring-white.svg?raw'
export { default as FilterIcon } from './filter-icon.svg?raw'
export { default as SortIcon } from './sort-icon.svg?raw'
export { default as Search } from './search.svg?raw'
export {default as Dots } from './dots.svg?raw'